K8s Helm init '--client-only' differs from EN-US Doc
https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm#configure-helm

As here EN-US doc says, without `--client-only`

$ helm init --client-only 
 
$HELM_HOME has been configured at /home/user/.helm. 
Not installing Tiller due to 'client-only' flag having been set 
Happy Helming! 

$ helm install stable/nginx-ingress
Error: could not find tiller

$ helm init 
$HELM_HOME has been configured at /home/user/.helm. 
 
Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster. 
Happy Helming!
 
$ helm install stable/nginx-ingress 
 
NAME: ordered-abalone 
LAST DEPLOYED: Thu Dec 21 04:58:14 2017 
NAMESPACE: default 
STATUS: DEPLOYED